name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          git submodule update --init --recursive
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: hdf5
          triplet: x64-windows-static-release
          token: ${{ github.token }}
          github-binarycache: true
      - name: cmake
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-release -DVCPKG_MANIFEST_MODE=OFF -DBUILD_SHARED_LIBS=OFF -DUSE_MSVC_RUNTIME_LIBRARY_DLL=OFF -DBUILD_STATIC_LIBS=ON -DVIAMD_ENABLE_VELOXCHEM=ON -DMD_UNITTEST=OFF -DMD_BENCHMARK=OFF . 
      - name: build
        run: |
          cmake --build . --config MinSizeRel -- /nologo /verbosity:minimal /maxcpucount:4
      - name: archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'viamd_win.zip'
          path: 'bin/MinSizeRel/.'
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            viamd_win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
