name: Ubuntu 24.04 (GCC 13)

on: [push]

jobs:
    ci:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v2
        - name: prepare
          run: |
            git submodule update --init --recursive
            sudo apt-get update
            sudo apt-get install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libgtk-3-dev pkgconf
        - name: cmake
          run: |
            cmake .
        - name: build
          run: |
            make -j 4
